// flow-typed signature: d6c5b3b7c05060fa5a9f648d0c5f261a
// flow-typed version: <<STUB>>/espower-babel_v^4.0.1/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'espower-babel'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'espower-babel' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'espower-babel/guess' {
  declare module.exports: any;
}

declare module 'espower-babel/lib/babelrc-util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'espower-babel/guess.js' {
  declare module.exports: $Exports<'espower-babel/guess'>;
}
declare module 'espower-babel/index' {
  declare module.exports: $Exports<'espower-babel'>;
}
declare module 'espower-babel/index.js' {
  declare module.exports: $Exports<'espower-babel'>;
}
declare module 'espower-babel/lib/babelrc-util.js' {
  declare module.exports: $Exports<'espower-babel/lib/babelrc-util'>;
}
